travis:
  secure:
    BINSTAR_TOKEN: tFd5CIl3HVTpWKmpSgjxpkPREyXOP8eopuot433bHsSz29NL6M85yMewAdQKG5oMha9alKaXH1wGXKj1o1L422IDcsA6+qkH209vGWrjaEVwnE5ZbeWSdIWILX2k6A43966yQGBvLcKqrp2riQJfkYQi4+iMXA4e3eMyc9V22ppDGPJiEmsHcqbpsBd9P5zjy4IVI9+YwyBz27mNHm3aSqmwqxdeLjo1NuFAJrQPjq5fcB3OIv8fD9GM9mMbEht6rhCcspX1dLiGS3xUWWLRXnbY9Vxwkc8sgFpTWh1EmCWvZPWrUV3gUV9OiIVbh/uamccJnU/E2tSUKog7TWAFYg9B/1toxLZtAZYUZvw3/lVyZ2lquIJQw4HhI2zcrrg8b6Y3Qil3KHCiGMOD30whru1cQCm2w4SxQCJK10fCFArUceUUCP8TkzRh93jsvarlpSd9PO12XS98jdF4dCuLDdqQWBbjby7NeGBkhemjPFbqdS/b9MIM4HbQBgQQkTga8GnJjAayQto2zL2YYOFIK6/9YtoLcftMxzwz1Cbp+4K+nSS9RFsYF+iMU6s5l2zYb8+8XFVjq04EHFVDrrsreYndBho5PTnvhgIq8z21ZA1rYnMdprWz0aTC2tT/cDotO8k36iPxhlG7CE2zx7pTc8czg0uB2EQtkyvkARdYZ/8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
