appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LAnMJWiEOdIWUsalcVwFPgRU3oA1h7iuSPCumAKv8Cf0EJdWSZ3Zfrn3eCB/IMIC6HnrDvEredF0zvTop0Ba+PRuN6C0wOIf/C4VcdBibNuJkQI2uvxXHqVEAqngLPjcc7T//ZHdU/EWKUzsdWqDz5lsyztEnl7bClPhcGRBCnvhF8cd/Ctx+bjAXlDLFCnYDRBx/bFos35cvVXgaYD4U9u+k65IDsjyadXUX1Ry6djo4pS9qTmFIPey6/pkP/F5narD1pOJjeORPpV95REqJUGYzwsweTq9UH6UgXKFSLjmTPy7TqcdzY4hEg1EvIlrfq8lWhDLtQWRDblugOZ2f9+miR81/rbWwZGlACFu6wmCSbpG6YdooSLbUW0hwvxHBndyXiOXgmHrxJLN2VbpYV3alS633ZjSxh2Ymut5TcMr2/RxtSfcqxe9F9ueCjOCtMr1i1v8g/6eEVcB41ZUM/bxqfIBw3CFWJWa/HeRi5LQuvgo3igHdcxIzMQbaw9PuGelylUO9kf0S16aem/jzfJQGYGw4ihPA0mIB4TeUbGziQeQfrrQWaTvUmfM30LD3IvsOv7wK8fEuBXs9tg5C89L0xIL9s3FFlcnom/M3WnL2c03F19ObquKRO+Ls6AxMj9r7B9cQQAgLQ1zo1LUZ9LOLJMmzsjA2ohwiWY9KXE=
conda_forge_output_validation: true
